apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtualrouter-controller-sa
  namespace: virtualrouter
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualrouter-controller-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  # - 'apps'
  # - 'extensions'
  # - 'core'
  # - ''
  # resources:
  # - 'deployments'
  # - 'namespaces'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# - apiGroups:
#   - 'rbac.authorization.k8s.io'
#   resources:
#   - 'rolebindings'
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtualrouter-controller-cluster-rb
  namespace: virtualrouter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtualrouter-controller-cluster-role
subjects:
- kind: ServiceAccount
  name: virtualrouter-controller-sa
  namespace: virtualrouter
---


apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: virtualrouter-controller-role
  namespace: virtualrouter
rules:
- apiGroups:
  - "tmax.hypercloud.com"
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: virtualrouter-controller-rb
  namespace: virtualrouter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: virtualrouter-controller-role
subjects:
- kind: ServiceAccount
  name: virtualrouter-controller-sa
  namespace: virtualrouter
---